services:
  app:
    image: php:8.3-apache
    container_name: larapad_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:8
    container_name: larapad_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: larapad
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: larapad_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4081:80"

volumes:
  mysql_data:
